export enum PrestationType {
  GENERADAS = 'GENERADAS',
  PAMIID = 'PAMIID',
  ID_ADULTO = 'ID_ADULTO',
  ID_PEDIATRICO = 'ID_PEDIATRICO',
  ANULADAS = 'ANULADAS',
  EN_SEGUIMIENTO = 'EN_SEGUIMIENTO',
}
